name: sms
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  dropdown_button2: ^2.3.9
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.3
  google_fonts: ^6.1.0
  hooks_riverpod: ^2.4.4
  riverpod_annotation: ^2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  riverpod_generator: ^3.0.0-dev.4
  build_runner: ^2.4.6
  custom_lint: ^0.5.3
  riverpod_lint: ^2.3.1

flutter:
  uses-material-design: true
