name: sms
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # l10n
  flutter_localizations:
    sdk: flutter
  intl: any

  # ui
  gap: ^3.0.1
  google_fonts: ^5.1.0

  # ui image
  image_picker: ^1.0.4
  image_picker_for_web: ^3.0.1
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.7

  # navigation
  auto_route: ^7.8.3

  # riverpod
  flutter_hooks: ^0.20.3
  flutter_riverpod: ^2.4.0
  hooks_riverpod: ^2.3.10
  riverpod_annotation: ^2.1.4
  riverpod_state: ^0.1.1

  # model
  faker: ^2.1.0
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1

  # form
  form_validator: ^2.1.1

  # cache
  shared_preferences: ^2.2.1
  flutter_animate: ^4.2.0+1
  dotted_line: ^3.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  riverpod_generator: ^2.3.1
  build_runner: ^2.4.6
  custom_lint: ^0.5.3
  riverpod_lint: ^2.0.3
  json_serializable: ^6.7.1
  freezed:
  auto_route_generator: ^7.3.1

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/illustrations/

